#!/usr/bin/env bash
#
# Run all installers.

source "$(dirname $0)/shared"

set -e

cd "$(dirname $0)"/..

exec 3>&1

# find the installers and run them
find . -name 'install.sh' | while read installer; do
  info "Running $installer"
  $($installer <&3 >&3)
  if [ $? -eq 0 ];
  then
    success "$installer completed"
  fi
done
