#!/usr/bin/env bash

source "$(dirname $0)/shared"

BASE="$HOME/.vim/bundle"

if [ "$1" = "log-since" ]; then
  echo "**logsince**"
  logsince="true"
  date="$2"
else
  logsince="false"
fi

if $($logsince) ; then
  echo "*** logsince ***"
fi

mkdir -p $BASE

action_from() {
  if [ -r $1 ]; then
    repos="$(cat $1)"
    for repo in $repos; do
      cd $BASE
      dir="$(basename $repo)"
      if [ -d "$BASE/$dir" ]; then
        cd "$BASE/$dir"
        if $logsince ; then
          echo "Log for repo $repo" >>/tmp/vimbundles.log
          git log --since $date --color=always >>/tmp/vimbundles.log
        else
          info "Updating $repo"
          git pull --rebase > /dev/null 2>&1
          if [ $? -eq 0 ];
          then
            success "Updated $repo"
          fi
        fi
      else
        info "Installing $repo"
        git clone https://github.com/"$repo".git > /dev/null 2>&1
        if [ $? -eq 0 ];
        then
          success "Installed $repo"
        fi
      fi
    done
  fi
}

action_from "$HOME/.vimbundle"
action_from "$HOME/.vimbundle.local"

if $logsince ; then
  less "/tmp/vimbundles.log"
  rm "/tmp/vimbundles.log"
fi
