#!/usr/bin/env bash

source $BEDROCK_DIR/libexec/shared

function install_pkg_manager () {
  # macOS - Homebrew
  if [ "$(uname -s)" == "Darwin" ]
  then
    if test ! "$(which brew)"
    then
      info "Installing Homebrew"
      ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
      if [ $? -eq 0 ];
      then
        success "Installed Homebrew"
      fi
    else
      info "Updating Homebrew"
      brew update >/dev/null
      success "Homebrew updated"
    fi
  fi
}

function install_zsh () {
  if [ `which zsh` != "/usr/local/bin/zsh" ]
  then
    brew install zsh
  fi

  if [ $SHELL != "/usr/local/bin/zsh" ]
  then
    info "Updating shell to zsh"
    SHELL_LINE="/usr/local/bin/zsh"
    sudo grep -qF "$SHELL_LINE" /etc/shells || echo "$SHELL_LINE" | sudo tee -a /etc/shells
    chsh -s "/usr/local/bin/zsh"
    info "You may wish to restart your Terminal sessions to ensure this takes effect"
  fi
}

command="$1"

case "$command" in
"dependencies" )
  install_pkg_manager
  install_zsh
  ;;
"dotfiles" )
  install_dotfiles
  ;;
esac