#!/usr/bin/env bash
# Summary: Display the version of bedrock
#
# Displays the version number of this mason release, including the
# current revision from git, if available.
#
# The format of the git revision is:
#   <version>-<num_commits>-<git_sha>
# where `num_commits` is the number of commits since `version` was
# tagged.
set -e
[ -n "$BEDROCK_DEBUG" ] && set -x

version="0.1"
git_revision=""

if cd $BEDROCK_DIR 2>/dev/null && git remote -v 2>/dev/null | grep -q bedrock; then
  git_revision="$(git describe --tags HEAD 2>/dev/null || true)"
  git_revision="${git_revision#v}"
fi

echo "bedrock ${git_revision:-$version}"