#!/usr/bin/env zsh
# Summary: Manage the bundle
# Usage: bedrock bundle [update\install]

source $BEDROCK_DIR/libexec/shared

while read -r line || [[ $line ]]; do
  extensions+=("$line")
done < $BEDROCK_DIR/bundle

extensionDirs=("${extensions[@]/#/$BEDROCK_DIR/extensions/}")

if [ "$1" = "install" ]; then
  install_dotfiles
  scripts=(${^extensionDirs}**/install.zsh(N))
  for s in $scripts
  do
    "$s"
    if [ $? -eq 0 ];
    then
      success "$s completed"
    else
      failure "$s failed"
    fi
  done
elif [ "$1" = "update" ]; then
  echo $extensionDirs
  
  for d in $extensionDirs
  do
    info "Updating $d "
    git -C $d pull
  done
  
  scripts=(${^extensionDirs}**/update.zsh(N))
  for s in $scripts
  do
    "$s"
    if [ $? -eq 0 ];
    then
      success "$s completed"
    else
      failure "$s failed"
    fi
  done
fi